- name: Set up Python
    uses: actions/setup-python@v5
    with:
      python-version: '3.x'

  - name: Run LINE Notifier
    env:
      LMS_ICAL_URL: ${{ secrets.LMS_ICAL_URL }}
      LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
      LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
    run: python main.py
